name: unit test on push
on: [ pull_request ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PRIVATE_TOKEN }}
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew --info kotest

      - name: 테스트 결과 Report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()  # 테스트가 실패하여도 Report를 보기 위해 `always`로 설정
        with:
          files: 'build/test-results/**/*.xml'

      - name: 테스트 실패 Comment
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: 'build/test-results/test/TEST-*.xml'